# ============================================================================
#  MailGuard Pro - first-time setup (Windows / PowerShell)
#
#  Generates your security secrets, asks for your license key and an admin
#  password, and writes a ready-to-run .env file. Safe to re-run.
#
#  Run from the MailGuard folder:
#      powershell -ExecutionPolicy Bypass -File .\setup.ps1
# ============================================================================

$ErrorActionPreference = "Stop"
Set-Location -Path $PSScriptRoot

$envPath = Join-Path $PSScriptRoot ".env"

# ── Don't silently destroy an existing configuration ────────────────────────
if (Test-Path $envPath) {
    $ans = Read-Host ".env already exists. Overwrite it? [y/N]"
    if ($ans -notmatch '^[Yy]$') {
        Write-Host "Keeping existing .env. Nothing changed." -ForegroundColor Yellow
        exit 0
    }
}

# ── Secret generators (cryptographically secure) ────────────────────────────
function New-RandomBytes([int]$count) {
    $bytes = New-Object 'System.Byte[]' $count
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
    return $bytes
}
function New-HexKey([int]$count) {
    ((New-RandomBytes $count) | ForEach-Object { $_.ToString('x2') }) -join ''
}
function New-Base64Key([int]$count) {
    [Convert]::ToBase64String((New-RandomBytes $count))
}

Write-Host ""
Write-Host "Generating security secrets..." -ForegroundColor Cyan
$PostgresPassword = New-HexKey 16
$SecretKey        = New-HexKey 32
$EncryptionKey    = New-Base64Key 32

# ── License key ─────────────────────────────────────────────────────────────
Write-Host ""
$License = (Read-Host "Paste your MailGuard license key").Trim()
while ([string]::IsNullOrWhiteSpace($License)) {
    $License = (Read-Host "License key cannot be empty. Paste it").Trim()
}

# ── Admin password (hidden input) ───────────────────────────────────────────
function Read-Plain([string]$prompt) {
    $sec = Read-Host $prompt -AsSecureString
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)
    try { [Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr) }
    finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
}

Write-Host ""
while ($true) {
    $AdminPassword  = Read-Plain "Choose an admin password (input hidden)"
    $AdminPassword2 = Read-Plain "Confirm admin password"
    if ([string]::IsNullOrWhiteSpace($AdminPassword)) { Write-Host "Password cannot be empty." -ForegroundColor Red; continue }
    if ($AdminPassword -ne $AdminPassword2)           { Write-Host "Passwords do not match - try again." -ForegroundColor Red; continue }
    break
}

# ── Optional: One-Click OAuth (Microsoft 365) ───────────────────────────────
# Most people skip this and connect from inside the app instead (easier).
$ClientId = ""; $ClientSecret = ""; $RedirectUri = ""
Write-Host ""
$enableOauth = Read-Host "Pre-fill Microsoft 365 One-Click OAuth now? Most people skip this (connect in-app later). [y/N]"
if ($enableOauth -match '^[Yy]$') {
    $ClientId     = (Read-Host "  Azure Application (client) ID").Trim()
    $ClientSecret = Read-Plain "  Client secret (hidden)"
    $RedirectUri  = (Read-Host "  Redirect URI (e.g. http://localhost:8000/api/auth/callback)").Trim()
}

# ── Build .env (string concatenation so special characters are written
#     literally; LF line endings + no BOM so Docker reads values cleanly) ─────
$stamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$lines = @(
    "# MailGuard Pro environment - generated by setup.ps1 on $stamp"
    "# Re-run setup.ps1 to regenerate. Keep this file private."
    ""
    "# -- License -------------------------------------------------------------"
    "MAILGUARD_LICENSE_KEY=" + $License
    ""
    "# -- Database (required) -------------------------------------------------"
    "POSTGRES_PASSWORD=" + $PostgresPassword
    ""
    "# -- Security (auto-generated - do not share) ----------------------------"
    "SECRET_KEY=" + $SecretKey
    "ENCRYPTION_KEY=" + $EncryptionKey
    ""
    "# -- Login ---------------------------------------------------------------"
    "AUTH_MODE=local"
    "ADMIN_PASSWORD=" + $AdminPassword
    ""
    "# -- Network (optional) --------------------------------------------------"
    "# Port MailGuard listens on. Uncomment and change if 8000 is already in use."
    "# PORT=8000"
    ""
    "# -- Microsoft 365 (optional - fill in to auto-register your tenant) -----"
    "SEED_TENANT_NAME="
    "SEED_TENANT_DOMAIN="
    "SEED_TENANT_ID="
    "SEED_CLIENT_ID="
    "SEED_CLIENT_SECRET="
    ""
    "# One-Click OAuth (optional; you can also set this from the web interface)"
    "MAILGUARD_CLIENT_ID=" + $ClientId
    "MAILGUARD_CLIENT_SECRET=" + $ClientSecret
    "MAILGUARD_REDIRECT_URI=" + $RedirectUri
    ""
    "# -- Optional integrations (add later from the web interface or here) ----"
    "ET_API_KEY="
    "ANTHROPIC_API_KEY="
    "ABUSEIPDB_API_KEY="
    "VT_API_KEY="
    "URLHAUS_AUTH_KEY="
    "SPAMHAUS_USERNAME="
    "SPAMHAUS_KEY="
    "AZURE_LOOKALIKE_BLOB_CONNECTION_STRING="
)
$content = ($lines -join "`n") + "`n"
[System.IO.File]::WriteAllText($envPath, $content, (New-Object System.Text.UTF8Encoding($false)))

Write-Host ""
Write-Host "Done. .env created." -ForegroundColor Green
Write-Host ""
Write-Host "Start MailGuard with:" -ForegroundColor Cyan
Write-Host "    docker compose pull"
Write-Host "    docker compose up -d"
Write-Host ""
Write-Host "Then open http://localhost:8000 and log in with the admin password you chose."
