#!/usr/bin/env bash
#
# MailGuard Pro — first-time setup.
#
# Generates the security secrets, collects your license key and a chosen admin
# password, and writes a ready-to-run .env file. Safe to re-run.
#
set -euo pipefail
cd "$(dirname "$0")"

ENV_FILE=".env"

command -v openssl >/dev/null 2>&1 || { echo "ERROR: 'openssl' is required but not installed."; exit 1; }

# Don't silently destroy an existing configuration.
if [ -f "$ENV_FILE" ]; then
  read -r -p ".env already exists. Overwrite it? [y/N] " ans
  case "$ans" in
    y|Y) : ;;
    *) echo "Keeping existing .env. Nothing changed."; exit 0 ;;
  esac
fi

echo "Generating security secrets..."
POSTGRES_PASSWORD="$(openssl rand -hex 16)"
SECRET_KEY="$(openssl rand -hex 32)"
ENCRYPTION_KEY="$(openssl rand -base64 32)"

echo
read -r -p "Paste your MailGuard license key: " LICENSE_KEY
while [ -z "$LICENSE_KEY" ]; do
  read -r -p "License key cannot be empty. Paste it: " LICENSE_KEY
done

echo
while true; do
  read -r -s -p "Choose an admin password (input hidden): " ADMIN_PASSWORD; echo
  read -r -s -p "Confirm admin password: " ADMIN_PASSWORD2; echo
  if [ -z "$ADMIN_PASSWORD" ]; then echo "Password cannot be empty."; continue; fi
  if [ "$ADMIN_PASSWORD" != "$ADMIN_PASSWORD2" ]; then echo "Passwords do not match - try again."; continue; fi
  break
done

# Write a clean, complete .env. Values are already expanded into shell variables,
# so special characters in the password/key are written literally and safely.
cat > "$ENV_FILE" <<EOF
# MailGuard Pro environment — generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Re-run ./setup.sh to regenerate. Keep this file private.

# ── License ───────────────────────────────────────────────────────────────────
MAILGUARD_LICENSE_KEY=${LICENSE_KEY}

# ── Database (required) ───────────────────────────────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ── Security (auto-generated — do not share) ──────────────────────────────────
SECRET_KEY=${SECRET_KEY}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# ── Login ─────────────────────────────────────────────────────────────────────
AUTH_MODE=local
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# ── Network (optional) ────────────────────────────────────────────────────────
# Port MailGuard listens on. Uncomment and change if 8000 is already in use.
# PORT=8000

# ── Microsoft 365 (optional — fill in to auto-register your tenant) ───────────
SEED_TENANT_NAME=
SEED_TENANT_DOMAIN=
SEED_TENANT_ID=
SEED_CLIENT_ID=
SEED_CLIENT_SECRET=

# ── Optional integrations (add later from the web interface or here) ──────────
ET_API_KEY=
ANTHROPIC_API_KEY=
ABUSEIPDB_API_KEY=
VT_API_KEY=
URLHAUS_AUTH_KEY=
SPAMHAUS_USERNAME=
SPAMHAUS_KEY=
AZURE_LOOKALIKE_BLOB_CONNECTION_STRING=
EOF

chmod 600 "$ENV_FILE"

echo
echo "Done. .env created and locked down (chmod 600)."
echo
echo "Start MailGuard with:"
echo "    docker compose up -d"
echo
echo "To connect a Microsoft 365 or Google Workspace tenant later, either fill the"
echo "SEED_ lines in .env, or add the tenant from the web interface after logging in."
